# -*- coding: utf-8 -*-
"""Proyecto taller de programación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-4tiaQIGDjxFcIV-GBc0PfjKChoUbuL
"""

import os # Libreria os si el archivo de texto existe
inventario = {} #se crea un diccionario vacío
class Dispositivo:
  #constructor, se inicializa los atributos
    def __init__(self, nombre, marca, modelo, ip, estado):
        self.nombre = nombre
        self.marca = marca
        self.modelo = modelo
        self.ip = ip
        self.estado = estado


#funcion 2.1
#interfaz del menú
def menu():
    cargar_datos() # Carga los datos guardados al iniciar

    opcion = ""
    #El menú se repetirá constantemente en bucle mientras la opción ingresada no sea "9"
    while opcion != "9":

        print("########################################")
        print("   GESTOR IP DE DISPOSITIVOS  ")
        print("==============================")
        print("1. Registro de nuevos equipos.")
        print("2. Visualización del inventario.")
        print("3. Búsqueda y consulta por IP.")
        print("4. Actualización del estado.")
        print("5. Generación de reportes.")
        print("6. Guardar datos en archivo.")
        print("7. Eliminar equipo por IP.")
        print("8. Eliminar todo el inventario.")
        print("9. Salir")

        opcion = input("Seleccione una opción (1-9): ")

        if opcion == "1":
            registro_nuevo_dispositivo()
        elif opcion == "2":
            visualizacion_inventario()
        elif opcion == "3":
            busqueda_por_ip()
        elif opcion == "4":
            actualizacion_estado()
        elif opcion == "5":
            generacion_reportes()
        elif opcion == "6":
            guardar_en_archivo()
        elif opcion == "7":
            eliminar_por_ip()
        elif opcion == "8":
            eliminar_todo()
        elif opcion == "9":
            guardar_en_archivo() # guarda automáticamente antes de cerrar
            print("Saliendo del sistema...")
        else:
            print("Opción inválida. Intente de nuevo.")
#-------------------------------------------------------------------------------
#  FUNCIÓN 2.2 - Validar formato de IP

def validar_ip(ip):
    #Se tomara como ejemplo la IPv4 osea:192.168.1.10
    # Tiene 4 números separados por puntos

    # Paso 1: Separar la IP en partes usando el punto como separador
    # Toma el texto y lo separa tras cada "." quedando una lista de string , esto se guarda en una variable llamada segmentos
    segmentos = ip.split(".") # split solo para texto

    # Paso 2:Luego se cuenta que tenga 4 partes
    if len(segmentos) != 4:
        print("Error: la IP debe tener exactamente 4 números separados por puntos.")
        return False

    # Paso 3: Revisar cada una de las 4 partes
    for segmento in segmentos:

        # toma cada elemento de la lista creada y verifica que sea un numero
        if segmento.isdigit() == False:
            print("Error: cada parte de la IP debe ser un número.")
            return False

        # Convertir el texto a número para poder hacer matematicas
        numero = int(segmento)

        #analiza si el numero de cada parte de "segmento" esta entre el rango 0 a 255
        if numero < 0 or numero > 255:
            print("Error: cada número de la IP debe estar entre 0 y 255.")
            return False

    # Si pasa por los tres filtros es una IP es válida
    return True
#-------------------------------------------------------------------------------
#función 2.3
def pedir_ip():
    # Esta función le pide la IP al usuario y no para hasta que ingrese una válida

    while True:
        ip = input("Ingrese la dirección IP (ejemplo: 192.168.1.10): ")

        # Llamamos a validar_ip para saber si lo que escribió está bien
        if validar_ip(ip) == True:
            # Si es válida, salimos del bucle y devolvemos la IP
            return ip
        else:
            # Si no es válida, avisamos y volvemos a preguntar
            print("La IP ingresada no es válida. Intente de nuevo.")
            print()
#-------------------------------------------------------------------------------
#  FUNCIÓN 2.4 - Validar texto (nombre, marca, modelo)


def validar_texto(texto, nombre_del_campo):
    # Esta función revisa que el texto no esté vacío
    # nombre_del_campo es solo para mostrar mensajes más claros
    # Por ejemplo: "nombre", "marca" o "modelo"

    # Paso 1: Se detecta si el usuario no escribrio nada y si solo puso espacios en blanco
    if texto == "" or texto.strip() == "":
        print("Error: el campo '" + nombre_del_campo + "' no puede estar vacío.")
        return False

    # Si tiene algo escrito, el texto es válido
    return True

#-------------------------------------------------------------------------------
#función 2.5
def pedir_texto(nombre_del_campo):
    # Esta función le pide un dato de texto al usuario
    # y no para hasta que escriba algo válido

    while True:
        texto = input("Ingrese " + nombre_del_campo + ": ")

        # Llamamos a validar_texto para revisar si está bien
        if validar_texto(texto, nombre_del_campo) == True:
            # Si es válido, devolvemos el texto
            return texto
        else:
            # Si no es válido, volvemos a preguntar
            print("Intente de nuevo.")
            print()

#-------------------------------------------------------------------------------
#Función 2.6
def registro_nuevo_dispositivo():
    print("Registro de nuevo equipo ")

    # Llama a la función pedir_ip de que valida internamente el bucle
    ip = pedir_ip()

    if ip in inventario:
        print("Error: Esta IP ya esta registrada en el sistema.")
        return

    # Llama a pedir_texto  para asegurar que no queden vacíos
    nombre = pedir_texto("el nombre del equipo")
    marca = pedir_texto("la marca")
    modelo = pedir_texto("el modelo")

    nuevo_disp = Dispositivo(nombre, marca, modelo, ip, True)
    inventario[ip] = nuevo_disp
    print("Dispositivo registrado con exito.")
#--------------------------------------------------------------------------------
#Función 2.7
#busca un equipo en específico usando la ip como llave
def busqueda_por_ip():
    print("Búsqueda por IP")
    ip_buscar = input("Ingrese la IP que desea buscar: ")

    if ip_buscar in inventario: #el diccionario permite saber si la ip existe usando el in
        disp = inventario[ip_buscar] #extrae el objeto
        if disp.estado == True:
            texto_estado = "Activo"
        else:
            texto_estado = "Inactivo"
            #muestra por consola
        print("Equipo encontrado:")
        print("Nombre:", disp.nombre)
        print("Marca:", disp.marca)
        print("Modelo:", disp.modelo)
        print("IP Completa:", disp.ip)
        print("Estado:", texto_estado)
    else:
        print("No se encontro ningun equipo con esa IP.")

#---------------------------------------------------------------------------------
#función 2.8
def actualizacion_estado():
    print("Actualizar Estado")
    ip_buscar = input("Ingrese la IP del equipo: ")

    if ip_buscar in inventario: #se busca el equipo en el diccionario
        disp = inventario[ip_buscar]
        if disp.estado == True:
            print("El estado actual es: Activo")
        else:
            print("El estado actual es: Inactivo")

        print("1. Cambiar a Activo")
        print("2. Cambiar a Inactivo")
        opcion = input("Seleccione una opción: ")
        #modificamos el atributo booleano según la opción elegida
        if opcion == "1":
            disp.estado = True
            print("Estado actualizado a Activo.")
        elif opcion == "2":
            disp.estado = False
            print("Estado actualizado a Inactivo.")
        else:
            print("Opción no válida. No se hicieron cambios.")
    else:
        print("No se encontró ningún equipo con esa IP.")
#-------------------------------------------------------------------------------------------
#Función 2.9
# Guarda los datos del diccionario utilizando try-finally en un archivo txt
def guardar_en_archivo():
    archivo = open("Inventario.txt", "w") #abre el archivo en modo escritura
    try:
        for ip in inventario: #recorre las ip guardada en el diccionario inventario
            disp = inventario[ip]
            linea = disp.nombre + ";" + disp.marca + ";" + disp.modelo + ";" + disp.ip + ";" + str(disp.estado) + "\n"
            archivo.write(linea) #escribe la línea generada dentro del archivo
        print("Datos guardados en Inventario correctamente.")
    finally:
        archivo.close()

#-----------------------------------------------------------------------------------------------------

#Función 2.10
def cargar_datos():
    if not os.path.exists("Inventario.txt"):  #revisa si el archivo existe
        print("El archivo Inventario no existe. Se creara uno nuevo al guardar.")
        return

    archivo = open("Inventario.txt", "r") #archivo en modo lectura
    try:
        for linea in archivo: #recorre línea por línea
            linea = linea.strip() #quita los saltos de línea y espacios
            if linea != "": #si la línea no esta completamente vacía se ejecuta
                datos = linea.split(";")
                nombre = datos[0]
                marca = datos[1]
                modelo = datos[2]
                ip = datos[3]

                if datos[4] == "True": #si esta activo, el estado saldrá con un texto llamado true, en caso contrario false
                    estado = True
                else:
                    estado = False

                nuevo_dispositivo = Dispositivo(nombre, marca, modelo, ip, estado)
                inventario[ip] = nuevo_dispositivo #se guarda en el diccionario, usando la ip como llave
        print("Datos cargados correctamente.")
    finally:
        archivo.close()

#---------------------------------------------------------------------------------------------------------

#función 2.11
def generacion_reportes():
    print("Reportes por Marca")
    marca_filtrar = input("Ingrese la marca a buscar: ")

    contador = 0 #cuenta cuántos equipos cumplen el criterio de búsqueda
    for ip in inventario: #se recorre el inventario completo
        disp = inventario[ip]
        if disp.marca.lower() == marca_filtrar.lower(): #Comparamos convirtiendo ambos textos a minúsculas (.lower()) para evitar problemas con mayúsculas
            ip_protegida = ocultar_ip(disp.ip) #se oculta la ip en la visualización del reporte
            if disp.estado == True:
                texto_estado = "Activo"
            else:
                texto_estado = "Inactivo"
            print("Nombre:", disp.nombre, "| Modelo:", disp.modelo, "| IP:", ip_protegida, "| Estado:", texto_estado)
            contador = contador + 1 #sumamos por cada equipo encontrado

    if contador == 0:
        print("No se encontraron equipos de esa marca.")
    else:
        print("Total de equipos encontrados:", contador)

#-------------------------------------------------------------------------------------------------------------------------

# Función 2.12
# para ocultar los últimos dos segmentos de la IP
def ocultar_ip(ip):
    partes = ip.split(".") #corta la ip en cada punto, genera una lista de 4 partes
    if len(partes) == 4:  # 1° estructura de control (if)
        nueva_ip = partes[0] + "." + partes[1] + ".*.*" #añade astericos a las 2 primeras partes
        return nueva_ip #devuelve una ip parcialmente oculta
    return ip #si falla algo devuelve la ip original

#--------------------------------------------------------------------------------------------------------------------------
#Función 2.13
def visualizacion_inventario():
    print("Inventario ")
    if len(inventario) == 0: #si el tamaño del diccionario es 0, esta vacío
        print("No hay equipos registrados.")
        return

    lista_equipos = [] #se crea una lista vacía
    for ip in inventario: #pasamos los datos del diccionario a una lista para iterar
        lista_equipos.append(inventario[ip])

    for disp in lista_equipos: # se recorre la lista uno por uno
        ip_protegida = ocultar_ip(disp.ip) #llama la función para ocultar la ip

        if disp.estado == True: #transforma el valor booleano a un texto para el usuario
            texto_estado = "Activo"
        else:
            texto_estado = "Inactivo"

        # guardamos los datos ordenados en una estructura de Tupla
        datos_dispositivo = (disp.nombre, disp.marca, disp.modelo, ip_protegida, texto_estado)

        # Imprimimos accediendo a las posiciones de la tupla
        print("Nombre:", datos_dispositivo[0], "| Marca:", datos_dispositivo[1], "| Modelo:", datos_dispositivo[2], "| IP:", datos_dispositivo[3], "| Estado:", datos_dispositivo[4])

    lista_marcas = [] #para guardas las marcas ya encontradas
    for disp in lista_equipos:
        if disp.marca not in lista_marcas: # analiza si la marca del equipo actual no esta en la lista
            lista_marcas.append(disp.marca) #se agrega a la lista

    print("Fabricantes únicos en la empresa:", len(lista_marcas)) #muestra el total de marcas sin repetir
    for m in lista_marcas:
        print("-", m)
#-------------------------------------------------------------------------------------------
#Función 2.14
# Elimina un solo dispositivo del diccionario usando su ip como llave
def eliminar_por_ip():
    print("Eliminar Equipo por IP")
    ip_eliminar = input("Ingrese la IP del equipo que desea eliminar: ")

    if ip_eliminar in inventario: # revisa si el equipo existe
        disp = inventario[ip_eliminar]
        print("Se eliminará el equipo:", disp.nombre, "de la marca:", disp.marca)

        confirmar = input("¿Está seguro de eliminarlo? (si/no): ")
        if confirmar.lower() == "si":
            del inventario[ip_eliminar] # Borra el equipo usando su llave ip
            print("Equipo eliminado con éxito.")
        else:
            print("Operación cancelada.")
    else:
        print("No se encontró ningún equipo con esa IP.")

#-------------------------------------------------------------------------------------------
#Función 2.15
# Borra absolutamente todos los datos guardados en el diccionario
def eliminar_todo():
    print("Eliminar Todo el Inventario")

    if len(inventario) == 0: #analiza si el diccionario inventario esta vacío
        print("El inventario ya está vacío.")
        return

    print("Esta opción borrará todos los equipos registrados.")
    confirmar = input("¿Está completamente seguro? Escriba 'SI' para confirmar: ")

    if confirmar == "SI":
        inventario.clear() # Vacía el diccionario por completo en un solo paso
        print("Todo el inventario ha sido eliminado.")
    else:
        print("Operación cancelada.")

#----------------------------------------------------------------------------------------


# Punto de partida oficial para ejecutar el programa
if __name__ == "__main__":
    menu()  # Inicializa la función del menú principal
